"""change default_model

Revision ID: 2f2838c488a5
Revises: 7e0a61edb6be
Create Date: 2023-02-16 11:52:07.043578

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2f2838c488a5'
down_revision = '7e0a61edb6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
