"""change default_model date fields

Revision ID: 34efb38b72d3
Revises: 2f2838c488a5
Create Date: 2023-02-16 11:53:49.630306

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '34efb38b72d3'
down_revision = '2f2838c488a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
