"""change default_model date field without default

Revision ID: a03d4c2fd3be
Revises: 34efb38b72d3
Create Date: 2023-02-16 14:27:56.539211

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a03d4c2fd3be'
down_revision = '34efb38b72d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
