"""change donation model

Revision ID: bb18b71d58b4
Revises: c9bbcdcd7a7c
Create Date: 2023-02-16 14:52:04.701697

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'bb18b71d58b4'
down_revision = 'c9bbcdcd7a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
